version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/precourse-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - h2-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-database:9092/~/sakak
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - app-network

  h2-database:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
