spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/sakak
    #    url: jdbc:h2:tcp://localhost/~/sakak
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # ddl-auto
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000

excel:
  path: 'src/main/resources/templates/nutrition_info.xlsx'
